# Generated by Django 3.1 on 2020-08-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=100)),
                ('Objective', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='image/')),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('School', models.CharField(max_length=100)),
                ('College', models.CharField(max_length=100)),
                ('Board', models.CharField(max_length=100)),
                ('Startdate', models.CharField(max_length=30)),
                ('Enddate', models.CharField(max_length=30)),
                ('CGPA', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=100)),
                ('Employer', models.CharField(blank=True, max_length=100)),
                ('Jobtitle', models.CharField(blank=True, max_length=100)),
                ('Jobcity', models.CharField(blank=True, max_length=100)),
                ('Jobstate', models.CharField(blank=True, max_length=100)),
                ('Jobstartdate', models.CharField(blank=True, max_length=100)),
                ('Jobenddate', models.CharField(blank=True, max_length=100)),
                ('Certification', models.CharField(blank=True, max_length=100)),
                ('Certificationlink', models.CharField(blank=True, max_length=100)),
                ('Skill1', models.CharField(blank=True, max_length=100)),
                ('Skill2', models.CharField(blank=True, max_length=100)),
                ('Skill3', models.CharField(blank=True, max_length=100)),
                ('Socialname1', models.CharField(blank=True, max_length=100)),
                ('Sociallink', models.CharField(blank=True, max_length=100)),
                ('Socialname2', models.CharField(blank=True, max_length=100)),
                ('Sociallink2', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
