# Generated by Django 3.1 on 2020-08-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resumedata',
            table='Resume',
        ),
    ]
