# Generated by Django 3.1 on 2020-08-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200813_0111'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resumedata',
            table=None,
        ),
    ]
