# Generated by Django 3.1 on 2020-08-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_resumedata_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='Board2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Branch',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Employer2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Jobcity2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Jobenddate2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Jobstartdate2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Jobstate2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='Jobtitle2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='School2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='UG',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
