# Generated by Django 3.1 on 2020-08-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200813_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='Skill4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
